// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Pet   string
	Toys  string
	Users string
}{
	Pet:   "pet",
	Toys:  "toys",
	Users: "users",
}
