// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Pets", testPets)
	t.Run("Toys", testToys)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Pets", testPetsDelete)
	t.Run("Toys", testToysDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Pets", testPetsQueryDeleteAll)
	t.Run("Toys", testToysQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Pets", testPetsSliceDeleteAll)
	t.Run("Toys", testToysSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Pets", testPetsExists)
	t.Run("Toys", testToysExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Pets", testPetsFind)
	t.Run("Toys", testToysFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Pets", testPetsBind)
	t.Run("Toys", testToysBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Pets", testPetsOne)
	t.Run("Toys", testToysOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Pets", testPetsAll)
	t.Run("Toys", testToysAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Pets", testPetsCount)
	t.Run("Toys", testToysCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Pets", testPetsHooks)
	t.Run("Toys", testToysHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Pets", testPetsInsert)
	t.Run("Pets", testPetsInsertWhitelist)
	t.Run("Toys", testToysInsert)
	t.Run("Toys", testToysInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("PetToUserUsingOwner", testPetToOneUserUsingOwner)
	t.Run("ToyToPetUsingPet", testToyToOnePetUsingPet)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("PetToToys", testPetToManyToys)
	t.Run("UserToOwnerPets", testUserToManyOwnerPets)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("PetToUserUsingOwnerPets", testPetToOneSetOpUserUsingOwner)
	t.Run("ToyToPetUsingToys", testToyToOneSetOpPetUsingPet)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("PetToUserUsingOwnerPets", testPetToOneRemoveOpUserUsingOwner)
	t.Run("ToyToPetUsingToys", testToyToOneRemoveOpPetUsingPet)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("PetToToys", testPetToManyAddOpToys)
	t.Run("UserToOwnerPets", testUserToManyAddOpOwnerPets)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("PetToToys", testPetToManySetOpToys)
	t.Run("UserToOwnerPets", testUserToManySetOpOwnerPets)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("PetToToys", testPetToManyRemoveOpToys)
	t.Run("UserToOwnerPets", testUserToManyRemoveOpOwnerPets)
}

func TestReload(t *testing.T) {
	t.Run("Pets", testPetsReload)
	t.Run("Toys", testToysReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Pets", testPetsReloadAll)
	t.Run("Toys", testToysReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Pets", testPetsSelect)
	t.Run("Toys", testToysSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Pets", testPetsUpdate)
	t.Run("Toys", testToysUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Pets", testPetsSliceUpdateAll)
	t.Run("Toys", testToysSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
